"""Subclass of EditDialog, which is generated by wxFormBuilder."""

import wx
import racm_ui


# Implementing EditDialog
class EditDialog(racm_ui.EditDialog):
    _main_frame = None
    _row = -1

    def __init__(self, parent, main_frame, host, port, name, row):
        racm_ui.EditDialog.__init__(self, parent)
        self._main_frame = main_frame
        self.port_text.SetValue(str(port))
        self.host_text.SetValue(host)
        self.port_text.SetValue(port)
        self.name_text.SetValue(name)
        self._row = row

    def show_dialog(self, message):
        dialog = wx.MessageDialog(None, message, self.GetTitle(), wx.OK | wx.ICON_WARNING)
        dialog.ShowModal()
        dialog.Destroy()

    def show_missing_error(self, value_type):
        self.show_dialog("Please input the " + value_type + ".")

    def show_illegal_error(self, value_type, character):
        self.show_dialog("Illegal character \"" + character + "\" contained in " + value_type + ".")

    # Handlers for EditDialog events.
    def on_ok_clicked(self, event):
        if self.host_text.IsEmpty():
            self.show_missing_error("host")
            return
        if ":" in self.host_text.Value:
            self.show_illegal_error("host", ":")
            return
        if self.port_text.IsEmpty():
            self.show_missing_error("port")
            return
        host = self.host_text.Value + ":" + self.port_text.Value
        self._main_frame.edit_item(host, self.name_text.Value, "", self._row)
        self.Destroy()

    def on_cancel_clicked(self, event):
        self.Destroy()
